# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Effortless Management
email: colestrode@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A very infrequently updated blog on software engineering management.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://colestro.de" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  colestrode

# Build settings
markdown: kramdown
include: ['_pages']

# Theme
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme 

# Dependencies
gems:
  - jekyll-redirect-from
