# Build settings
plugins:
  - jemoji
  - jekyll-paginate

# Site settings
title: "The Effortless Manager"
description: Yet Another Blog about engineering management

email: cole@theeffortlessmanager.com
logo: "/assets/images/em_logo.jpeg" #blog logo
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/cover.jpg"

name: 'Cole Strode'
author: 'Cole Strode'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "https://theeffortlessmanager.com" # the base hostname & protocol for your site
baseurl: ""

timezone: "America/New_York"
future: false # hide future posts
unpublished: false # hide unpublished posts


#google_analytics: UA-XXXXX-X
google_tag_manager: G-FXJL4J0WT7

# social icons and sharing options
social:
#  - icon:	twitter
#    url:	https://twitter.com/dirkfabisch
#    desc: Follow me on twitter
#    share_url: http://twitter.com/share
#    share_title: ?text=
#    share_link: "&amp;url="

  - icon:	github
    url:	https://github.com/colestrode
    desc:	Find me on Github
    share_url:
    share_title:
    share_link:

  - icon:	linkedin
    url:	https://www.linkedin.com/in/colestrode/
    desc:	This is my corporate face
    share_url:
    share_title:
    share_link:
